name: summer2022
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  path_provider_android: ^2.0.11
  global_configuration: ^2.0.0-nullsafety.0
  speech_to_text: ^5.6.0
  flutter_tts: ^3.5.0
  xml: ^6.1.0
  http: ^0.13.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_mlkit_barcode_scanning: ^0.3.0
  image_picker: ^0.8.5+3
  googleapis_auth: ^1.3.1
  googleapis: ^9.1.0
  json_serializable: ^6.2.0
  flutter_svg: ^1.1.0
  toggle_switch: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  camera: ^0.9.8+1
  url_launcher: ^6.1.4
  flutter_secure_storage: ^5.0.2
  enough_mail: ^2.1.1
  loader_overlay: ^2.0.7
  permission_handler: ^10.0.0
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  build_runner: ^2.1.11

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  test: ^1.21.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/credentials.json
    - assets/Image1.png
    - assets/rectangle4.svg
    - assets/rectangle5.svg
    - assets/cfg/
    - assets/horusx.jpg
    - assets/mail.test.01.jpg
    - assets/mail.test.02.png
    - assets/mail.test.03.png
    - assets/NoAttachments.png
    - assets/mail.test.04.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
