name: iOS CI/CD

on:
  push:
    branches:
      - "master"
      - "developer"
  
  pull_request:
    branches:
      - "master"
      - "developer"
      
jobs:
 deploy_ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - name: Get run number
        run: |
          echo '${{ github.run_number }}'
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Set up cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
            podfile-path: ios/Podfile.lock
      - run: flutter pub get
      - run: pod install
      - run: flutter build ios --release --no-codesign
